---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  namespace: default
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      serviceAccountName: prd-example-app
      containers:
        - name: example-app
          image: us-central1-docker.pkg.dev/poc-kubernetes-459003/prd-images-example-app/default:latest
          # envFrom:
          #   - secretRef:
          #       name: example-app-db-secret
          resources:
            requests:
              memory: 32Mi
              # cpu: 100m
            limits:
              memory: 64Mi
              # cpu: 100m
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: example-app-gke-spc-volume
              mountPath: "/mnt/example-app-gke-spc"
              readOnly: true
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy@sha256:c5a6a06ce9038293937368713fbff78f924acbc2bf7e82d822ab9bbc4e49ec72
          command:
            - "/cloud-sql-proxy"
            - "poc-kubernetes-459003:us-central1:prd-db-example-app"
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: example-app-gke-spc-volume
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "example-app-gke-spc"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - example-app
                topologyKey: "kubernetes.io/hostname"
