---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: example-app-gke-spc
  namespace: default
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/poc-kubernetes-459003/secrets/prd-secret_example-app-db_example-app_user/versions/latest"
        fileName: "example-app-db-user"
      - resourceName: "projects/poc-kubernetes-459003/secrets/prd-secret_example-app-db_example-app_pass/versions/latest"
        fileName: "example-app-db-pass"
  # secretObjects:
  #   - secretName: example-app-db-secret
  #     type: Opaque
  #     data:
  #       - objectName: example-app-db-user
  #         key: MYSQL_USER
  #       - objectName: example-app-db-pass
  #         key: MYSQL_PASSWORD
